### ISSUE TITLE
other method is better than if.

### ISSUE THREAD

**Issue by konojunya** [City-of-Kobe/bizwastesearch#3]
https://github.com/City-of-Kobe/bizwastesearch/blob/ef4638a9010dc5e71a6f48e7a5b6a7a7a734b924/code/script/script.js#L1312

上記のコードは非常に読みにくいように思えるのでmapにした方が良さそうです。

## mapped

```js
const LinkWodMap = {
  "あ": "A",
  "い": "A"
}

LinkWod = LinkWodMap[t_Left]
```

もしくは同じようなLinkWodがあるのでswitchで書いても良さそうです。

## switch

```js
switch(t_Left) {
  case "あ",
  case "い",
  case "う",
  case "え",
  case "お":
     return "A"
}
```

これはt_Leftのひらがなの列の変換をしていふように思えるので、`charCodeAt` を使ってutf-16のコード表から抜き取ると言うもう少しテクニカルな変換も可能ですが可読性が落ちそうなので提案だけにしておきます。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

**Comment by SKosaka** [comment]
ご指摘いただきありがとうございます。
確かにここの部分は長いなぁと思いながら書いていたので、早速ご教示いただいた方法でやってみます。

**Comment by SKosaka** [comment]
@konojunya 
実装しました。
ご教示いただきありがとうございます。
